# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# The SBOM tasks have been removed because they are not required for the unofficial template.
# You can manually enable SBOM in the unofficial template if needed, othewise its automatically enabled when using official template. https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sbom
# This pipeline will be extended to the OneESPT template
# If you are not using the E+D shared hosted pool with windows-2022, replace the pool section with your hosted pool, os, and image name. If you are using a Linux image, you must specify an additional windows image for SDL: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#how-to-specify-a-windows-pool-for-the-sdl-source-analysis-stage
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: drop' in the templateContext section.
trigger: none
schedules:
  - cron: "0 7 1 * *"
    displayName: Monthly Run
    branches:
      include:
        - refs/heads/dev17
    always: true
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
  - repository: VCLS-Extensions
    type: git
    name: VCLS-Extensions
    ref: refs/heads/dev17
variables:
- name: ApiScanClientId
  value: 1d6a3de7-4a6a-4b75-b15d-e305293c75af
- name: ApiScanSecret
  value: "$(TAfBTAPIScanSecret)"
- name: ApiScanTenant
  value: 72f988bf-86f1-41af-91ab-2d7cd011db47
- name: ArtifactServices.Symbol.AccountName
  value: devdiv
- name: ArtifactServices.Symbol.PAT
  value: "$(BoostTestSymbolsPat)"
- name: ArtifactServices.Symbol.UseAAD
  value: false
- name: BuildConfiguration
  value: "$(TAfBTBuildConfiguration)"
- name: BuildPlatform
  value: Any CPU
- name: CodeQL.Enabled
  value: True
- name: CodeQL.TSAEnabled
  value: True
- name: DropRoot
  value: '\\cpvsbuild\drops'
- name: Packaging.EnableSBOMSigning
  value: "$(TAfBTEnableSBOMSigning)"
- name: ProductComponent
  value: "$(TAfBTProductComponent)"
- name: Publish
  value: "$(TAfBTPublish)"
# Quick build is used to skip some compliance tasks to quickly generate a .vsix for testing.
- name: QuickBuild
  value: "$(TAfBTQuickBuild)"
- name: TAfBTRealSign
  value: "$(RealSign)"
- name: RetainBuild
  value: "$(TAfBTRetainBuild)"
- name: SignType
  value: "$(TAfBTSignType)"
- name: TeamName
  value: VCLS
- name: VersionNumber
  value: "$(TAfBTVersionNumber)"
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022GPT-1ES
    sdl:
      sourceAnalysisPool:
        name: VSEngSS-MicroBuild2022-1ES
      sourceRepositoriesToScan:
        exclude:
        # No need to scan this source as we only use this repo to copy the public signing key.
        - repository: VCLS-Extensions
      tsa:
        enabled: true
        configFile: '$(Build.SourcesDirectory)\vs-boost-unit-test-adapter\TSAOptions.json'
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
        analyzeTargetGlob: '$(Build.ArtifactStagingDirectory)\FilesToScanDrop\**\*.dll'
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Phase_1
        displayName: Phase 1
        timeoutInMinutes: 0
        cancelTimeoutInMinutes: 1
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: drop'
            targetPath: $(Build.ArtifactStagingDirectory)\drop
        steps:
        - checkout: self
          displayName: 'Checkout vs-boost-unit-test-adapter Git Repo'
          clean: true
          fetchDepth: 1
          persistCredentials: true
        - checkout: VCLS-Extensions
          displayName: 'Checkout VCLS-Extensions ADO Repo to copy public key'
          clean: true
          fetchDepth: 1
          persistCredentials: true
        - task: NuGetToolInstaller@1
          displayName: Install NuGet
          inputs:
            versionSpec: 5.9.1
        - task: ms-vseng.MicroBuildTasks.a0262b21-fb8f-46f8-bb9a-60ed560d4a87.MicroBuildLocalizationPlugin@1
          displayName: Install Localization Plugin
        - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@4
          displayName: Install Signing Plugin
          inputs:
            signType: $(SignType)
        - task: ms-vseng.MicroBuildTasks.32f78468-e895-4f47-962c-58a699361df8.MicroBuildSwixPlugin@4
          displayName: Install Swix Plugin
        - task: PowerShell@2
          displayName: Set Version
          inputs:
            targetType: filePath
            filePath: './vs-boost-unit-test-adapter/SetVersion.ps1'
            arguments: '-version $(VersionNumber)'
        - task: CopyFiles@2
          displayName: 'Copy FinalPublicKey.snk to vs-boost-unit-test-adapter'
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/VCLS-Extensions/InternalAPIs/DevDiv'
            Contents: 'FinalPublicKey.snk'
            TargetFolder: '$(Build.SourcesDirectory)/vs-boost-unit-test-adapter'
        - task: PowerShell@1
          displayName: Add Keys for RealSign to TAfBT
          inputs:
            scriptType: inlineScript
            inlineScript: |-
              $projects_to_sign = @(
                "vs-boost-unit-test-adapter\Antlr.DOT\Antlr.DOT.csproj",
                "vs-boost-unit-test-adapter\BoostTestAdapter\BoostTestAdapter.csproj",
                "vs-boost-unit-test-adapter\BoostTestPackage\BoostTestPackage.csproj",
                "vs-boost-unit-test-adapter\BoostTestPlugin\BoostTestPlugin.csproj",
                "vs-boost-unit-test-adapter\BoostTestShared\BoostTestShared.csproj",
                "vs-boost-unit-test-adapter\ThirdPartySigning\ThirdPartySigning.csproj",
                "vs-boost-unit-test-adapter\VisualStudioAdapter\VisualStudioAdapter.csproj"
              )
              $projects_to_sign | ForEach-Object {
                $xml = [xml](Get-Content $_)
                $KeyFile = $xml.CreateElement("AssemblyOriginatorKeyFile", "http://schemas.microsoft.com/developer/msbuild/2003")
                $KeyFile.set_InnerXML("`$(EnlistmentRoot)FinalPublicKey.snk")
                $xml | ForEach-Object { $_.Project.PropertyGroup | ForEach-Object { if ($_.Condition -like '*(RealSign)'' == ''True''') { $_.AppendChild($KeyFile) } } }
                $xml.Save("$pwd\$_")
              }
        - task: NuGetCommand@2
          displayName: NuGet restore for ThirdPartySigning and MicroBuild.Core
          inputs:
            solution: vs-boost-unit-test-adapter/swix/packages.config
            selectOrConfig: config
            nugetConfigPath: vs-boost-unit-test-adapter/NuGet.config
            noCache: true
            packagesDirectory: NuGetPackages
        - task: NuGetCommand@2
          displayName: NuGet restore
          inputs:
            solution: vs-boost-unit-test-adapter/BoostTestAdapter.sln
            selectOrConfig: config
            nugetConfigPath: vs-boost-unit-test-adapter/NuGet.config
            noCache: true
        - task: VSBuild@1
          displayName: Build solution BoostTestAdapter.sln
          inputs:
            solution: vs-boost-unit-test-adapter/BoostTestAdapter.sln
            platform: $(BuildPlatform)
            configuration: $(BuildConfiguration)
            maximumCpuCount: true
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\drop'
          inputs:
            Contents: '**\out\binaries\**'
            TargetFolder: $(Build.ArtifactStagingDirectory)\drop
        - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
          displayName: 'Manifest Generator '
          inputs:
            BuildDropPath: '$(Build.ArtifactStagingDirectory)\drop'
            PackageName: 'Test Adapter for Boost.Test'
            PackageVersion: 1.1.0.4
        - task: NuGetCommand@2
          displayName: NuGet restore for vsmanproj
          inputs:
            solution: vs-boost-unit-test-adapter/swix/packages.config
            selectOrConfig: config
            nugetConfigPath: vs-boost-unit-test-adapter/NuGet.config
            noCache: true
            packagesDirectory: ..\NugetPackages
          continueOnError: true
        - task: VSBuild@1
          displayName: Build vsmanproj
          condition: and(succeeded(), eq(variables['ProductComponent'], true))
          inputs:
            solution: vs-boost-unit-test-adapter/swix/Microsoft.VisualStudio.VC.Ide.TestAdapterForBoostTest.vsmanproj
            msbuildArgs: /p:ArtifactsDir=$(Build.ArtifactStagingDirectory)
            platform: $(BuildPlatform)
            configuration: $(BuildConfiguration)
        - task: CopyFiles@2
          displayName: Copy setup files to drop root
          inputs:
            SourceFolder: vs-boost-unit-test-adapter\out\binaries\$(BuildConfiguration)\Microsoft.VisualStudio.VC.Ide.TestAdapterForBoostTest
            Contents: '*'
            TargetFolder: $(Build.ArtifactStagingDirectory)\drop
          continueOnError: true
        - task: CopyFiles@2
          displayName: Copy vsix to root
          inputs:
            SourceFolder: vs-boost-unit-test-adapter\out\binaries\$(BuildConfiguration)\BoostTestPlugin
            Contents: BoostUnitTestAdapter.vsix
            TargetFolder: $(Build.ArtifactStagingDirectory)\drop
          continueOnError: true
        # Pull a list only of files we build and ship to be scanned in FilesToScanDrop.
        - task: PowerShell@2
          displayName: 'Copy Scannable Files to: $(Build.ArtifactStagingDirectory)\FilesToScanDrop'
          inputs:
            filePath: './vs-boost-unit-test-adapter/FilesToScan.ps1'
            arguments: '-buildArtifactStagingDirectory $(Build.ArtifactStagingDirectory) -directoryToSearch $(Build.ArtifactStagingDirectory)\drop'
        # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
        - task: PoliCheck@2
          displayName: 'PoliCheck on vs-boost-unit-test-adapter repo'
          condition: eq (variables.QuickBuild, False)
          inputs:
            targetType: 'F'
            targetArgument: '$(Build.SourcesDirectory)/vs-boost-unit-test-adapter'
        # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
        - task: securedevelopmentteam.vss-secure-development-tools.build-task-apiscan.APIScan@2
          displayName: 'Run APIScan'
          condition: eq (variables.QuickBuild, False)
          inputs:
            softwareFolder: '$(Build.ArtifactStagingDirectory)\FilesToScanDrop'
            softwareName: BoostTest
            softwareVersionNum: 1.0
            isLargeApp: false
            toolVersion: 'Latest'
            verbosityLevel: silent
            continueOnError: true
          env:
            AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
        # This is a time-consuming compliance task, so if we want to run a quick build (off by default), then we skip this task.
        - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@3
          displayName: 'Publish Guardian Artifacts'
          condition: eq (variables.QuickBuild, False)
          inputs:
            PublishProcessedResults: true
          continueOnError: true
        - task: 1ES.MicroBuildVstsDrop@1
          displayName: Upload VSTS Drop
          inputs:
            dropFolder: $(Build.ArtifactStagingDirectory)\drop
            dropName: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
            accessToken: $(System.AccessToken)
            dropServiceUri: https://devdiv.artifacts.visualstudio.com/DefaultCollection
            vsDropServiceUri: "https://vsdrop.corp.microsoft.com/file/v1"
        - task: ms-vseng.MicroBuildShipTasks.4a4e1dc3-01d0-484f-94ac-f918aaf7d509.MicroBuildRetainVstsDrops@1
          displayName: Retain VSTS Drops
          condition: and(succeeded(), eq(variables['RetainBuild'], true))
          inputs:
            DropNames: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
            AccessToken: $(System.AccessToken)
            DropServiceUri: https://devdiv.artifacts.visualstudio.com/DefaultCollection
        - task: PublishSymbols@2
          displayName: Publish symbols path
          inputs:
            SymbolsFolder: $(Build.ArtifactStagingDirectory)\drop
            SearchPattern: '**/*.pdb'
            SymbolServerType: TeamServices
            TreatNotIndexedAsWarning: true
        - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
          displayName: Perform Cleanup Tasks
          condition: always()